version: 2

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck


    - revive
    - misspell

    - gocritic
    - gosec
    - prealloc
    - unconvert
    - unparam

linters-settings:


  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - funlen
        - gognit
        - gocyclo
